### ISSUE TITLE
find a better incubation period dist

### ISSUE THREAD

**Issue by AugustHao** [infectious-disease-ecology-modelling/GPreff#18]
the current one is too concentrated

**Comment by smwindecker** [comment]
Check what is available in Epiparams package.
If that is not available, Freya says find a good paper from within the metaanalysis - and use that one.
Currently function only works with "Omicron" strain.

For generic package, clean up so that it is reasonable for variaous uses.

**Comment by smwindecker** [comment]
option 1: exemplar parameters for GI and IP for variety of pathogens
option 2: user specify
> interface with epiparams

**Comment by AugustHao** [comment]
also for the time being can use M Plank's https://www.medrxiv.org/content/10.1101/2023.08.14.23294060v1.full.pdf

**Comment by AugustHao** [comment]
Michael's group used this:
Weibull with mean 2.9 days and standard deviation 2.0 days

estimated by this paper
https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2022.27.6.2200042

seems reasonably reliable, can sub in this for now

**Comment by AugustHao** [comment]
done but should reopen when epiparams updates
