### ISSUE TITLE
make nowcast window

### ISSUE THREAD

**Issue by AugustHao** [infectious-disease-ecology-modelling/GPreff#30]
finish the completion matrix code to enable us to date the start of nowcast (first day when completion prob < 1). Change the plotting function to put in a greybox for the nowcasting period, when producing reff and infection plots (can repurpose the type = "forecast" code inside the plotting for this)

Suggest Saras for this task since she's already working on the completion matrix

**Comment by AugustHao** [comment]
need to look into using completion prob < 0.95 due to long tail in delay prob mass

**Comment by AugustHao** [comment]
fixed issue in completion prob calculation

**Comment by AugustHao** [comment]
first pass implemented in d070603

**Comment by smwindecker** [comment]
make it state specific

**Comment by AugustHao** [comment]
note need to better integrate the output of the nowcast starting date with the plotting function
