### ISSUE TITLE
make CAR and local cases input processing independent from old code base

### ISSUE THREAD

**Issue by AugustHao** [infectious-disease-ecology-modelling/GPreff#33]
need to extract the CAR matrix and local cases input codes from the old code base so we can run these data processing without going through the old clunky codebase

**Comment by SeniorKate** [comment]
Also watermelon and confirmation plots, possibly? Or some variant of that for data checking purposes

**Comment by AugustHao** [comment]
yes to confirmation plot, probably not watermelon because we are not convolving symptom dates anymore

**Comment by SeniorKate** [comment]
Possibly just keep in old codebase and figure out how to make model output work with that seeing as only two months left

**Comment by SeniorKate** [comment]
moved to sit-assessment specific repository

**Comment by SeniorKate** [comment]
moved to sit-assessment specific repository
