### ISSUE TITLE
curve-wise credible interval for visualising timeseries posteriors

### ISSUE THREAD

**Issue by AugustHao** [infectious-disease-ecology-modelling/GPreff#40]
current ribbon plot plots sampled point-wise CI values, need to change to curve-wise CI to better represent uncertainty in timeseries trajectories

**Comment by smwindecker** [comment]
https://search.r-project.org/CRAN/refmans/ggdist/html/curve_interval.html
https://mjskay.github.io/ggdist/articles/lineribbon.html#curve-boxplots-aka-lineribbons-with-joint-intervals-or-curvewise-intervals
